### ISSUE TITLE
Makefile execution issues

### ISSUE THREAD

**Issue by bobio2018** [Zilliqa/savant-ide#10]
A couple of issues when I run `makefile`, the first two are resolved however I am stuck at issue 3

**Issue 1**
No permission to clone Zilliqa/scilla repo to local
line 35
```
scilla-src:
	git clone git@github.com:Zilliqa/scilla
```

my solution is:
 - Generate SSH key using ssh-keygen -t rsa -b 4096 -C "your_email@example.com".
 - Copy the output of cat id_rsa.pub using 
```
cat /Users/<user>/.ssh/id_rsa.pub
```
 - Paste the above copied outpur into your Github profile -> Settings -> SSH and GPG Keys -> Add new SSH key

**Issue 2**
No switch 4.06.1 is currently installed.
```
	[ERROR] No switch 4.06.1 is currently installed. Did you mean 'opam switch
        create 4.06.1'?
```

My solution is to change line 44
from
```
opam switch -y 4.06.1
```
to
```
opam switch create -y 4.06.1
```
**Issue 3**

Dune no such file or directory

```
# Run eval $(opam env) to update the current shell environment
eval `opam config env`
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C scilla all
dune build @install
make[1]: dune: No such file or directory
make[1]: *** [all] Error 1
make: *** [scilla-bin] Error 2
```

**Comment by iantanwx** [comment]
@bobio2018 thanks for logging this issue. It seems to me that this is caused due to `dune` not being correctly installed (it is something like `webpack`, but for OCaml). I think it is breaking due to issue 2. Can you try manually running `opam install dune`, and then execute `make` again?

**Comment by bobio2018** [comment]
this has been resolved by running the full version makefile
