### ISSUE TITLE
Multi-signature wallet contract causes IDE to show blank screen

### ISSUE THREAD

**Issue by jjcnn** [Zilliqa/savant-ide#11]
I am trying to write a multi-singnature wallet, and have gotten to a point which doesn't raise an error when running scilla-checker manually. (See https://github.com/Zilliqa/scilla/commit/38cecc6818d08f9958960d4df9a935861022d551).

However, when I paste the code into the web IDE and press the "Check" button, I just get a completely blank screen:

![blank](https://user-images.githubusercontent.com/38888011/46210924-74ca5b80-c332-11e8-84d7-f92f03e6b858.png)

I am using Firefox 62.0.

**Comment by iantanwx** [comment]
@jjcnn Thanks for logging this issue. I'll get to it as soon as I can, which is likely next week or the week after. There are some corner cases that still need to be worked out server-side.

**Comment by iantanwx** [comment]
Related to #7 and can most likely be resolved with the same fix.

**Comment by AmritKumar** [comment]
@iantanwx Is ide-next.zilliqa.com still alive?

**Comment by iantanwx** [comment]
This now works in the latest version.
