### ISSUE TITLE
when you start a contract, an error pops up

### ISSUE THREAD

**Issue by lich666dead** [Zilliqa/savant-ide#38]
×
TypeError: Cannot read property 'reduce' of undefined
new InitForm
src/browser/components/Runner/InitForm.tsx:77
  74 | 
  75 | export default class InitForm extends React.Component<Props, State> {
  76 |   state: State = {
> 77 |     init: this.props.abiParams.reduce(
  78 |       (acc, { name, type }) => ({
  79 |         ...acc,
  80 |         [name]: { value: '', type, touched: false, error: false },
View compiled
▶ 17 stack frames were collapsed.
(anonymous function)
src/browser/components/Runner/Deploy.tsx:149
  146 | api
  147 |   .checkContract(code, ctrl.signal)
  148 |   .then((res) => {
> 149 |     this.setState({ isChecking: false, abi: JSON.parse(res.message) });
  150 |   })
  151 |   .catch((err) => {
  152 |     this.setState({ error: err.response ? err.response.message : err });

**Comment by iantanwx** [comment]
Thanks. This should be fixed by #36. I’ll close this and ping you again when it’s fixed, so that you can retry your contract.
