### ISSUE TITLE
Empty string named contract cannot be renamed after blur 

### ISSUE THREAD

**Issue by noelyoo** [Zilliqa/savant-ide#6]
### Problem
Empty string named contract cannot be renamed after blur 

### Steps To Reproduce

1. Create new contract.

2. Leave and blur with empty string.

3. Try to rename.

![sep-21-2018 08-16-27](https://user-images.githubusercontent.com/25740248/45851601-c09b6480-bd76-11e8-8af7-d212d86cbf02.gif)

### Possible Fixes
Are users allowed to set contract as empty string?
If true,
we can add deplay like 500ms Navigator/File.tsx#L84. There might be a better solution and I would like to see it.
https://github.com/Zilliqa/savant-ide/blob/master/src/browser/components/Navigator/File.tsx#L84

If Not true,
we can enforce a default value like 'noname'

**Comment by iantanwx** [comment]
@noelyoo thanks for bringing this to our attention. No, I think we don't want users to be able to set an empty string as the contract name. I prefer the second suggestion. This means if the string is empty, I think we can simply revert to the last known state (sometimes it may be only 1 character). Perhaps the default value is the best solution after all. @AmritKumar do you have any thoughts?

**Comment by iantanwx** [comment]
@noelyoo would you like to submit a PR for this issue? :)

**Comment by noelyoo** [comment]
@iantanwx Sure, if it's not urgent I would like make a PR for this issue with setting the default value for name.

**Comment by noelyoo** [comment]
@iantanwx I created a PR here: https://github.com/Zilliqa/savant-ide/pull/13
