### ISSUE TITLE
Check doesn't work on code with error 

### ISSUE THREAD

**Issue by KaganRoman** [Zilliqa/savant-ide#7]
Open Hello World scilla file, change in line 11 Message to Mesage, and press Check

White page is appeared, no error handling. This is exception:
<img width="1264" alt="screen shot 2018-09-21 at 8 12 53 pm" src="https://user-images.githubusercontent.com/4031217/45895776-c3c83c00-bdda-11e8-9f8e-9c8876175f15.png">

Tested on latest chrome version

**Comment by iantanwx** [comment]
Verified this, will fix. It's due to an unexpected response coming down from the server.
