### ISSUE TITLE
Erroneous line mark doesn't disappear when error has been fixed.

### ISSUE THREAD

**Issue by jjcnn** [Zilliqa/savant-ide#9]
When checking an erroneous contract, a marker occurs on the erroneous line:

![error_line_marker](https://user-images.githubusercontent.com/38888011/46072714-56722d80-c183-11e8-9184-4cbde9e30f24.png)

When fixing the error and pressing "Check" again, the marker does not disappear, even though the green box with "Type-checking succeeded" is displayed:

![error_line_marker_still_there](https://user-images.githubusercontent.com/38888011/46072780-7bff3700-c183-11e8-8c8b-785c74334b66.png)

I am using Firefox 62.0 on Ubuntu Linux. I have also tried on Chrome, but the same issue occurs. I have also tried to play around with my cookie settings, but the behaviour does not seem to change.

**Comment by iantanwx** [comment]
Thanks @jjcnn! I will look into this as soon as possible.

**Comment by iantanwx** [comment]
Fixed!
